# Generated by Django 5.2.14 on 2026-07-07 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto. Mínimo 3 caracteres.', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones y apóstrofes.', regex="^[\\w\\s\\-\\']+$")])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo aceptado: 1000.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen. Solo se permiten formatos de imagen válidos.', max_length=1024, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('categoria', models.CharField(blank=True, help_text='Categoría del producto.', max_length=120, null=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones y apóstrofes.', regex="^[\\w\\s\\-\\']+$")])),
                ('tipo_venta', models.CharField(blank=True, choices=[('fisico', 'Físico'), ('digital', 'Digital'), ('servicio', 'Servicio')], help_text='Tipo de venta del producto.', max_length=50, null=True)),
                ('etiqueta_precio', models.CharField(blank=True, help_text='Etiqueta de precio opcional.', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='La etiqueta de precio solo puede contener letras, números, espacios, guiones y apóstrofes.', regex="^[\\w\\s\\-\\']*$")])),
                ('cantidad', models.IntegerField(blank=True, help_text='Cantidad disponible. No puede ser negativa.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
